// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Yaba.Common;
using Yaba.Entities;

namespace Yaba.Entities.Migrations
{
    [DbContext(typeof(YabaDBContext))]
    partial class YabaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BudgetId");

                    b.Property<Guid?>("GoalId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("GoalId")
                        .IsUnique()
                        .HasFilter("[GoalId] IS NOT NULL");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<Guid?>("CategoryId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<Guid?>("BudgetId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Recurrence");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<int>("Recurrence");

                    b.HasKey("Id");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<Guid?>("BudgetId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Recurrence");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Category", b =>
                {
                    b.HasOne("Yaba.Entities.BudgetEntities.Budget", "Budget")
                        .WithMany("Categories")
                        .HasForeignKey("BudgetId");

                    b.HasOne("Yaba.Entities.BudgetEntities.Goal", "Goal")
                        .WithOne("Category")
                        .HasForeignKey("Yaba.Entities.BudgetEntities.Category", "GoalId");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Entry", b =>
                {
                    b.HasOne("Yaba.Entities.BudgetEntities.Category", "Category")
                        .WithMany("Entries")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Expense", b =>
                {
                    b.HasOne("Yaba.Entities.BudgetEntities.Budget", "Budget")
                        .WithMany("Expenses")
                        .HasForeignKey("BudgetId");
                });

            modelBuilder.Entity("Yaba.Entities.BudgetEntities.Income", b =>
                {
                    b.HasOne("Yaba.Entities.BudgetEntities.Budget", "Budget")
                        .WithMany("Incomes")
                        .HasForeignKey("BudgetId");
                });
#pragma warning restore 612, 618
        }
    }
}
